### ISSUE TITLE
Moodle 4.0 Compatibility

### ISSUE THREAD

**Issue by jrchamp** [Syxton/moodle-block_massaction#13]
While the release is not yet final, there's a lot of helpful information at https://docs.moodle.org/dev/Moodle_4.0_developer_update

In addition to manually testing the 4.0beta+ in a running environment, it may be worthwhile to add the `master` branch from upstream Moodle to the CI workflow.

If you have already done manual testing against the Moodle 4.0beta, then adding it to the list of compatible versions in the Moodle plugins directory may allow you to qualify for the Early Bird - Moodle 4.0 badge!

**Comment by PhMemmel** [comment]
We haven't targeted 4.0 yet because there are a lot of changes to the course formats. So, without having tried yet, I'd say there's a 90% chance that the plugin will not work with 4.0 out of the box, but feel free to share your experience :-)

I'm planning on reworking the structure of the plugin to use the new course editor javascript modules which will be available in 4.0. As this is a bigger rework on how the plugin works I'll probably do this on a separate 4.0 branch, because this would clean up the current code by a lot. I also wanted to wait a little bit to see if the maintainers of the common course formats will rewrite their format plugins to use the new course editor modules.

I'm probably going to tackle this in the next few weeks.

**Comment by Syxton** [comment]
@jrchamp @PhMemmel  I have tested an earlier revision of massactions on a Moodle 4.0 beta.  The core course formats were in working (but not perfect) order.  However, 3rd party course formats that I tested (grid, button) are in pretty bad shape currently.  I believe that Collapsed Topics has kept up their code for 4.0 already, but I don't remember if massactions worked on it.

I will go ahead and create a 4.0 branch.  I can add master testing to that branch (and remove everything under 4.0).

**Comment by PhMemmel** [comment]
Thank you for having a look!

I think we can drop support for Collapsed Topics (topcoll) anyway because the core "topics" format in moodle 4.0 already supports collapsable topics. So there's a good chance there won't be a topcoll format for 4.0 anyway.

Thanks for creating the 4.0 branch. I will develop the refactoring changes directly into that one as soon as I have the time for that, but won't happen before at least 2-3 weeks.

**Comment by PhMemmel** [comment]
Just to document this: AFAIK support for indentation will be optional for moodle 4.0 course formats, defaulting to "not available". So block_massaction has to read this config from the current course format and react to it.

**Comment by Syxton** [comment]
@PhMemmel Closing as the 4.0 branch is now master.  Any 4.0 compatibility issues are now just.....issues.  :)
