### ISSUE TITLE
Allow custom course formats

### ISSUE THREAD

**Issue by jrm-unamur** [Syxton/moodle-block_massaction#37]
Hi there,
Since v6.0.0 release commit, this plugin is only accessible to a hard-coded list of course formats.
Make this list configurable is handled in master branch but not on release tags.
Do you plan to add this functionality soon to the release on moodle plugins database?

Regards

**Comment by PhMemmel** [comment]
Hi @jrm-unamur,

IIRC we wanted to wait for most of the standard plugin formats (onetopic, tiles etc.) to release a working adapted version for moodle 4.0 (current `master` of block_massaction is moodle 4.0 only). This is because we do not want to raise the impression that these formats are supported, because they are not working at all yet. Once they will have a release for moodle 4.0, we'll add tests (see open PRs) and add them to the default supported list.

The configuration option was meant to be able to support non-standard course format plugins because we cannot cover all available course formats plugins with tests etc.

**Comment by jrm-unamur** [comment]
Hi @PhMemmel and thanks for prompt answer,
I clearly understand your point, but won't it be possible to backport the setting stuff to pre 4 version, so that anyone using your plugin may apply it to a local course format (at their own risks). I'm maintaining 2 course formats in moodle plugin database (collapsibletopics and collapsibleweeks, copy of core formats but with a much simple collapsing behaviour than that of collapsedtopics). 
Since moodle 4 implements such a behaviour, I'm not sure I will continue maintaining these plugins but since we won't move to moodle 4.0 before mid-2023, I still need them for a while.
If it's not possible for you to backport the setting, let me know and I'll do it locally
Regards

**Comment by PhMemmel** [comment]
Main reason for not backporting this probably would be the adaption of the necessary upgrade steps across branches and versions. I'm not 100% sure if this would complicate anything. Any thought on this @Syxton ?

**Comment by Syxton** [comment]
@jrm-unamur I have thought about backporting some of the best changes of the master branch back to 3.11.  I haven't had time to look into how difficult it would be, but I will take a look at this soon.

**Comment by Syxton** [comment]
@PhMemmel This backport seems to be good.  Can you check it out and see if there is anything you see? #40

**Comment by Syxton** [comment]
@PhMemmel Answering your previous question, I included the logic and the upgrade script, but I don't see any reason to spend the time working on the testing for course formats for the 3.11 version.  I think it is good enough to add the config and let admins decide which formats to support.  But if someone else feels the need, the infrastruture is there to make it easier.

**Comment by Syxton** [comment]
#40 backports this config setting to 3.11 version

**Comment by jrm-unamur** [comment]
@Syxton and @PhMemmel thanks for this backport, seems to work smoothly
Regards
