### ISSUE TITLE
Q: Is it possible for Moodle Admins to find any course to send duplicate to?

### ISSUE THREAD

**Issue by cdipe** [Syxton/moodle-block_massaction#61]
This is a great tool for managing courses! Question: Is there a permission to set for Moodle administrators so they can duplicate course resources to courses they are not added to? Our Learning Technicians would like to use this, but they are only added at category context, not course context.

**Comment by Syxton** [comment]
@PhMemmel This should probably be a setting. "Duplicate to course limited by enrollment"  What do you think?

**Comment by cdipe** [comment]
@Syxton if it could be a permission to be set for different roles it would be great!

**Comment by Syxton** [comment]
@cdipe I should have been more clear.  If you set the limittoenrolled to false, it still will require the person have the permission of moodle/restore:restoretargetimport in the target course.  This permission can be altered for your site, but generally is allowed for Teacher and Admins/Managers of site and category levels.

**Comment by PhMemmel** [comment]
The implementation decision was to limit the courses to the ones which the user is enrolled in, because on very big moodle instances with a lot of courses this will result in big performance issues (loading times of 30s and more, request timeouts), so it was safer to use `limittoenrolled=true` there. But we can make this configurable, no big deal, yes.

**Comment by cdipe** [comment]
@Syxton @PhMemmel thank you!

**Comment by cdipe** [comment]
Wonderful!
