### ISSUE TITLE
Request: show/hide description

### ISSUE THREAD

**Issue by fxpar** [Syxton/moodle-block_massaction#69]
Is there a way to add an action: show description / hide description for each selected module?
(it juste writes 1 or 0 in the column "showdescription" of the course_module table).
Thanks

**Comment by PhMemmel** [comment]
Thank you for the suggestion. I think this should be possible.

What comes to my mind thinking about this (this new feature would mean two more rows in the block)... Are there any more actions like this you have in mind? Because I'd like to somehow prevent the block from becoming too long. So if there are any more actions like these, maybe it's worth to redirect to a separate page or use another kind of design element to avoid making the block too long.

**Comment by fxpar** [comment]
Hi, 
Thanks for you answer.
I think the showdescription action could indeed be created "easily" from a copy of the set_visibility action (even a simplified version of it, but there can always be unexpected complications).
Unfortunately, I do not understand the templating code... And I totally get your concern about adding more actions.

You are right, some other columns of the course_modules table could be added (although for now I don't have use for them):

- groupmode
- lang
- completionview

I am as bad a designer as a coder, so, please, do not follow blindly my ideas, but here is the kind of thing I could think of to add more actions: 

![screen_20221219_143830](https://user-images.githubusercontent.com/11584406/208438474-46239e87-c6f3-4c88-8200-910f501c3982.png)

![screen_20221219_143845](https://user-images.githubusercontent.com/11584406/208438472-00d9118a-5fab-4d90-be53-78f83114df49.png)

I used the standard html:

`<details><summary>See more actions...</summary></details>`


Cheers

**Comment by PhMemmel** [comment]
Thank you very much for your suggestions and the input. They will be taken into consideration!
