### ISSUE TITLE
Mass Actions Block Background Tasks Hanging

### ISSUE THREAD

**Issue by ldh007bucknell** [Syxton/moodle-block_massaction#79]
We are running version 4.1.4 of Moodle and v. 7.1.3 of the Mass Actions block.

We have experienced a frequent issue of the "duplicate_task" in the Mass Actions block being sent to the background, where it never completes itself.  Right now, I see two of those tasks that have been running for over 16 hours.  (I took a screen capture when it was just under 16 hours.)

I am not sure what specific task the user was trying to accomplish that still hasn't completed.  We already restarted services a few days ago to clear a similar problem.  

I am attaching that screen capture file, in case it gives you clues about what I can check, to determine the actual process that is hanging.  

The "Maximum amount of course modules to duplicate" was set at the default amount of 5.  I am wondering if someone was trying to duplicate too many course modules, which led the task to be sent to the background, where it never completes.

Leslie Harris
Bucknell University
ldh007@bucknell.edu

<img width="896" alt="Administration_ Server_ Tasks_ Tasks_running_now-08-03-2023" src="https://github.com/Syxton/moodle-block_massaction/assets/36862887/ae1f1ea0-fbfc-4f1f-8d6c-dde124c028a2">

**Comment by PhMemmel** [comment]
Thank you for opening this issue.

First of all let me explain how the block works: Depending on the activity instance duplicating can require quite some time and resources. Because of that the block has the admin setting you mentioned: If a user selects x (default is 5) or more activities, the duplicating will be done as an adhoc background task. Below x activities it will be done directly in the same request, so the user will see the page loading while Moodle is duplicating the activities which can run into a webserver timeout if it takes too long.

So, if you see a duplicate adhoc task, a user has tried to duplicate more than 5 activities and the task tries to duplicate them.

Unfortunately, without any further information it is not possible to say anything more about what could be wrong in your instance or if this is a bug of block_massaction.

If possible, please provide the log data of the stuck adhoc task. If you have access to the database directly, you also may want to have a look at the task_adhoc table. The column customdata will contain all the course module ids which are trying to be duplicated. Once found out you might want to try to duplicate them directly in the course and see if this works. Probably there is something wrong with them :-)

Let us know if you had success debugging :-)

**Comment by PhMemmel** [comment]
Hi, thank you very much for providing some additional details.

It looks like there are only 8 activites being duplicated there. However, duplicating them seem to take a huge amount of time. I am wondering what kind of activities these are. From the logs you should be able to tell which course and which activities these are. Will you be able to share what kind of activities these are? Are you able to do a backup and restore of the course and measure how long this would take?

For explanation: Duplicating is basically a backup followed by a restore process.

The reason I am asking is: block_massaction basically uses the moodle core routines for duplicating. If it now takes hours for duplicating 8 activites I really wonder if this is due to the (apparently very slow) way block_massaction uses the core routines or if these are just activities which take the same amount of time when being duplicated without block_massaction.

Thanks in advance!

**Comment by Syxton** [comment]
When we have seen issues like this it was due to very large file activities or folder activities.  It takes a long time to zip and then unzip large files.  Videos were always our main pain point until we pushed all videos to an external service.  Closing.
